# Generated by Django 6.0.4 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolsession',
            name='photos_count',
        ),
        migrations.AddField(
            model_name='patrolsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrolsession',
            name='shift_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
