# Generated by Django 6.0.4 on 2026-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0002_remove_patrolsession_photos_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolsession',
            name='photos_count',
            field=models.IntegerField(default=0),
        ),
    ]
