# Generated by Django 6.0.4 on 2026-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0003_patrolsession_photos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolsession',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patrolsession',
            name='trail_coordinates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
