# Generated by Django 6.0.4 on 2026-04-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0004_patrolsession_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolsession',
            name='violations_count',
            field=models.IntegerField(default=0),
        ),
    ]
