# Generated by Django 6.0.4 on 2026-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0005_patrolsession_violations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolsession',
            name='violations_count',
            field=models.IntegerField(default=0, help_text='Number of violations recorded during this patrol'),
        ),
    ]
