# Generated by Django 6.0.7 on 2026-10-03 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0006_alter_patrolsession_violations_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('month', models.IntegerField(help_text='1=Jan, 2=Feb, etc.')),
                ('year', models.IntegerField()),
                ('is_manual', models.BooleanField(default=False, help_text='True if Director manually assigned this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('officer', 'month', 'year')},
            },
        ),
    ]
