# Generated by Django 6.0.7 on 2026-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0007_patrolassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolZoneMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
