# Generated by Django 6.0.4 on 2026-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('rule_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('penalty_1st', models.CharField(default='Warning', max_length=255)),
                ('penalty_2nd', models.CharField(default='Parental Consultation', max_length=255)),
                ('penalty_3rd', models.CharField(default='SDAO Referral', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
