# Generated by Django 6.0.4 on 2026-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbookentry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='penalty_4th',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handbookentry',
            name='penalty_5th',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='penalty_1st',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='penalty_2nd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='penalty_3rd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='rule_code',
            field=models.CharField(help_text='e.g. 27.3.1.20', max_length=20, unique=True),
        ),
    ]
