# Generated by Django 6.0.4 on 2026-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='clearance_status',
            field=models.CharField(choices=[('CLEARED', 'Cleared'), ('HOLD', 'Hold')], default='CLEARED', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
