# Generated by Django 6.0.4 on 2026-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_id_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
