# Generated by Django 6.0.7 on 2026-08-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreedomWallSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('submission_type', models.CharField(choices=[('Complaint', 'Complaint / Reklamo'), ('Suggestion', 'Suggestion'), ('Feedback', 'General Feedback'), ('Concern', 'Report a Concern'), ('Appreciation', 'Appreciation')], max_length=50)),
                ('category', models.CharField(choices=[('Professor', 'Professor / Faculty'), ('Subject', 'Subject / Curriculum'), ('Administration', 'School Administration'), ('Student Services', 'Student Services'), ('Facilities', 'Facilities'), ('Bullying', 'Bullying / Harassment'), ('Safety', 'Safety & Security'), ('Welfare', 'Student Welfare'), ('Policies', 'School Policies'), ('Activities', 'Student Activities'), ('Other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('student_reported_priority', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('official_priority', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Acknowledged', 'Acknowledged'), ('Under Review', 'Under Review'), ('For Investigation', 'For Investigation'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freedom_wall_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_to', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Referred', 'Referred'), ('Acknowledged', 'Acknowledged'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fw_referrals', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='freedom_wall.freedomwallsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fw_responses', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='freedom_wall.freedomwallsubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
