# Generated by Django 6.0.7 on 2026-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedomwallsubmission',
            name='submission_type',
            field=models.CharField(choices=[('report_something', 'Report Something'), ('get_help', 'Get Help'), ('resolve_conflict', 'Resolve a Conflict'), ('suggest_improvement', 'Suggest an Improvement'), ('share_experience', 'Share Your Experience'), ('give_appreciation', 'Give Appreciation')], max_length=50),
        ),
    ]
