# Generated by Django 6.0.7 on 2026-08-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_wall', '0002_alter_freedomwallsubmission_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedomwallsubmission',
            name='resolution_file',
            field=models.FileField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
