# Generated by Django 6.0.7 on 2026-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_wall', '0003_freedomwallsubmission_resolution_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedomwallsubmission',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freedomwallsubmission',
            name='visibility',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Community', 'Community'), ('Private', 'Private'), ('Hidden', 'Hidden')], default='Pending Review', max_length=50),
        ),
    ]
