# Generated by Django 6.0.4 on 2026-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_wall', '0006_communityreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedomwallsubmission',
            name='category',
            field=models.CharField(choices=[('General Feedback', 'General Feedback'), ('School Concern', 'School Concern'), ('Officer Report', 'Officer Report'), ('Professor', 'Professor / Faculty'), ('Subject', 'Subject / Curriculum'), ('Administration', 'School Administration'), ('Student Services', 'Student Services'), ('Facilities', 'Facilities'), ('Bullying', 'Bullying / Harassment'), ('Safety', 'Safety & Security'), ('Welfare', 'Student Welfare'), ('Policies', 'School Policies'), ('Activities', 'Student Activities'), ('Other', 'Other')], max_length=50),
        ),
    ]
