# Generated by Django 6.0.4 on 2026-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_violation_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='director_remarks',
            field=models.TextField(blank=True, help_text="Justification/remarks for the Director's decision.", null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='director_sanction',
            field=models.CharField(blank=True, help_text='Formal sanction rendered by the Director.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('PENDING', 'Pending Decision'), ('RESOLVED', 'Resolved'), ('APPEALED', 'Appealed')], default='OPEN', max_length=20),
        ),
    ]
