# Generated by Django 6.0.4 on 2026-04-25 16:34

from django.db import migrations, models


def convert_statuses(apps, schema_editor):
    Violation = apps.get_model('violations', 'Violation')
    # Map old statuses to new institutional flow
    # 1. UNDER_REVIEW (ongoing) -> OPEN
    Violation.objects.filter(status='UNDER_REVIEW').update(status='OPEN')
    # 2. PENDING (waiting for decision) -> AWAITING_DECISION
    Violation.objects.filter(status='PENDING').update(status='AWAITING_DECISION')
    # 3. APPEALED -> AWAITING_DECISION (returns to director queue)
    Violation.objects.filter(status='APPEALED').update(status='AWAITING_DECISION')
    # 4. RESOLVED -> CLOSED
    Violation.objects.filter(status='RESOLVED').update(status='CLOSED')

class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0003_violation_director_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_DECISION', 'Awaiting Decision'), ('DECISION_RENDERED', 'Decision Rendered'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.RunPython(convert_statuses),
    ]
