# Generated by Django 6.0.4 on 2026-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0004_update_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
