# Generated by Django 6.0.4 on 2026-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_violation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Auto-populated from location_name lookup', null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='location_name',
            field=models.CharField(blank=True, help_text='Normalized location key matching the DLSUD_LOCATIONS lookup table', max_length=255),
        ),
        migrations.AddField(
            model_name='violation',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Auto-populated from location_name lookup', null=True),
        ),
    ]
