# Generated by Django 6.0.4 on 2026-10-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_clearance_status_and_more'),
        ('violations', '0006_violation_latitude_violation_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='users.studentprofile')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='violations.violation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
