# Generated by Django 6.0.4 on 2026-10-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0007_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('AWAITING_INFO', 'Awaiting Student Info'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
